// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Generator = require("../../builder/modules/Generator.bs.js");

function requireImage(id) {
  return require("./images/" + id + ".png");
}

function requireTexture(id) {
  return require("./textures/" + id + ".png");
}

var id = "minecraft-chest";

var name = "Minecraft Chest";

var history = ["Originally developed by minecraftpapercrafttemplates."];

var thumbnail = {
  url: require("./thumbnail/thumbnail-256.jpeg")
};

var imageIds = ["Background"];

function toImageDef(id) {
  return {
          id: id,
          url: requireImage(id)
        };
}

var images = imageIds.map(toImageDef);

var textures = [{
    id: "Chest",
    url: requireTexture("Chest"),
    standardWidth: 640,
    standardHeight: 640
  }];

function script(param) {
  Generator.defineTextureInput("Chest", {
        standardWidth: 640,
        standardHeight: 640,
        choices: []
      });
  Generator.drawImage("Background", [
        0,
        0
      ]);
  Generator.drawTextureLegacy("Chest", {
        x: 281,
        y: 140,
        w: 139,
        h: 49
      }, {
        x: 221,
        y: 385,
        w: 76,
        h: 27
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 140,
        y: 141,
        w: 139,
        h: 49
      }, {
        x: 449,
        y: 385,
        w: 76,
        h: 27
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 0,
        y: 140,
        w: 139,
        h: 49
      }, {
        x: 373,
        y: 385,
        w: 76,
        h: 27
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 421,
        y: 140,
        w: 139,
        h: 49
      }, {
        x: 297,
        y: 385,
        w: 76,
        h: 27
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 281,
        y: 0,
        w: 139,
        h: 141
      }, {
        x: 297,
        y: 308,
        w: 77,
        h: 77
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 140,
        y: 0,
        w: 139,
        h: 141
      }, {
        x: 298,
        y: 412,
        w: 77,
        h: 77
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 283,
        y: 190,
        w: 139,
        h: 141
      }, {
        x: 298,
        y: 489,
        w: 77,
        h: 79
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 280,
        y: 330,
        w: 139,
        h: 100
      }, {
        x: 221,
        y: 567,
        w: 77,
        h: 55
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 421,
        y: 330,
        w: 139,
        h: 100
      }, {
        x: 298,
        y: 567,
        w: 78,
        h: 55
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 0,
        y: 330,
        w: 139,
        h: 100
      }, {
        x: 374,
        y: 567,
        w: 77,
        h: 55
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 142,
        y: 330,
        w: 139,
        h: 100
      }, {
        x: 451,
        y: 567,
        w: 77,
        h: 55
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 142,
        y: 192,
        w: 139,
        h: 139
      }, {
        x: 307,
        y: 622,
        w: 78,
        h: 78
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 10,
        y: 0,
        w: 20,
        h: 10
      }, {
        x: 487,
        y: 490,
        w: 11,
        h: 5
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 30,
        y: 0,
        w: 20,
        h: 10
      }, {
        x: 487,
        y: 517,
        w: 11,
        h: 5
      }, "Vertical", undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 10,
        y: 10,
        w: 20,
        h: 40
      }, {
        x: 487,
        y: 495,
        w: 11,
        h: 22
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 0,
        y: 10,
        w: 10,
        h: 40
      }, {
        x: 482,
        y: 495,
        w: 5,
        h: 22
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 30,
        y: 10,
        w: 10,
        h: 40
      }, {
        x: 498,
        y: 495,
        w: 5,
        h: 22
      }, undefined, undefined, undefined, undefined);
  Generator.drawTextureLegacy("Chest", {
        x: 40,
        y: 10,
        w: 20,
        h: 40
      }, {
        x: 502,
        y: 495,
        w: 11,
        h: 22
      }, undefined, undefined, undefined, undefined);
}

var generator_thumbnail = thumbnail;

var generator = {
  id: id,
  name: name,
  history: history,
  thumbnail: generator_thumbnail,
  video: undefined,
  instructions: undefined,
  images: images,
  textures: textures,
  script: script
};

var instructions = "\n  ## Welcome to the Chest generator!\n  ### This is still in Beta Development\n  ### Upload a texture of your own chest or select a chest already provided for you!\n  ### Unfortunately, I couldn't make the folds transparent, so I will let someone else do the job. :(\n";

exports.requireImage = requireImage;
exports.requireTexture = requireTexture;
exports.id = id;
exports.name = name;
exports.history = history;
exports.thumbnail = thumbnail;
exports.instructions = instructions;
exports.imageIds = imageIds;
exports.toImageDef = toImageDef;
exports.images = images;
exports.textures = textures;
exports.script = script;
exports.generator = generator;
/* thumbnail Not a pure module */
